version: '3.1'

services:
  db:
    image: postgres
    container_name: rok_dev_db
    restart: always
    ports:
     - "5431:5432"
    environment:
      POSTGRES_PASSWORD: thisisapassword
    volumes:
      - ./devdb-data:/var/lib/postgresql/data
